# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'databaseBrowser.ui'
#
# Created: Wed Jun 24 12:46:17 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1175, 674)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(60, 50, 241, 211))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.operatorComboBox = QtGui.QComboBox(self.verticalLayoutWidget)
        self.operatorComboBox.setObjectName("operatorComboBox")
        self.gridLayout.addWidget(self.operatorComboBox, 2, 1, 1, 1)
        self.comboBox_5 = QtGui.QComboBox(self.verticalLayoutWidget)
        self.comboBox_5.setObjectName("comboBox_5")
        self.gridLayout.addWidget(self.comboBox_5, 4, 1, 1, 1)
        self.osmolyteLabel = QtGui.QLabel(self.verticalLayoutWidget)
        self.osmolyteLabel.setObjectName("osmolyteLabel")
        self.gridLayout.addWidget(self.osmolyteLabel, 3, 0, 1, 1)
        self.macroMoleculeLabel = QtGui.QLabel(self.verticalLayoutWidget)
        self.macroMoleculeLabel.setObjectName("macroMoleculeLabel")
        self.gridLayout.addWidget(self.macroMoleculeLabel, 1, 0, 1, 1)
        self.macroMoleculeComboBox = QtGui.QComboBox(self.verticalLayoutWidget)
        self.macroMoleculeComboBox.setObjectName("macroMoleculeComboBox")
        self.gridLayout.addWidget(self.macroMoleculeComboBox, 1, 1, 1, 1)
        self.operatorLabel = QtGui.QLabel(self.verticalLayoutWidget)
        self.operatorLabel.setObjectName("operatorLabel")
        self.gridLayout.addWidget(self.operatorLabel, 2, 0, 1, 1)
        self.setTypeLabel = QtGui.QLabel(self.verticalLayoutWidget)
        self.setTypeLabel.setObjectName("setTypeLabel")
        self.gridLayout.addWidget(self.setTypeLabel, 0, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.osmolyteComboBox = QtGui.QComboBox(self.verticalLayoutWidget)
        self.osmolyteComboBox.setObjectName("osmolyteComboBox")
        self.gridLayout.addWidget(self.osmolyteComboBox, 3, 1, 1, 1)
        self.setTypeComboBox = QtGui.QComboBox(self.verticalLayoutWidget)
        self.setTypeComboBox.setObjectName("setTypeComboBox")
        self.gridLayout.addWidget(self.setTypeComboBox, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.findSetButton = QtGui.QPushButton(self.verticalLayoutWidget)
        self.findSetButton.setObjectName("findSetButton")
        self.verticalLayout.addWidget(self.findSetButton)
        self.plotButton = QtGui.QPushButton(self.centralwidget)
        self.plotButton.setGeometry(QtCore.QRect(490, 250, 110, 32))
        self.plotButton.setObjectName("plotButton")
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(40, 290, 341, 341))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_6 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.listWidget = QtGui.QListWidget(self.verticalLayoutWidget_2)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_2.addWidget(self.listWidget)
        self.verticalLayoutWidget_3 = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(650, 30, 481, 551))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget = QtGui.QWidget(self.verticalLayoutWidget_3)
        self.widget.setObjectName("widget")
        self.verticalLayout_3.addWidget(self.widget)
        self.clearPlotButton = QtGui.QPushButton(self.centralwidget)
        self.clearPlotButton.setGeometry(QtCore.QRect(490, 280, 110, 32))
        self.clearPlotButton.setObjectName("clearPlotButton")
        self.addToPlotButton = QtGui.QPushButton(self.centralwidget)
        self.addToPlotButton.setGeometry(QtCore.QRect(390, 440, 121, 32))
        self.addToPlotButton.setObjectName("addToPlotButton")
        self.saveDataButton = QtGui.QPushButton(self.centralwidget)
        self.saveDataButton.setGeometry(QtCore.QRect(490, 310, 110, 32))
        self.saveDataButton.setObjectName("saveDataButton")
        self.dataListView = QtGui.QListView(self.centralwidget)
        self.dataListView.setGeometry(QtCore.QRect(370, 40, 256, 192))
        self.dataListView.setObjectName("dataListView")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar()
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1175, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.osmolyteLabel.setText(QtGui.QApplication.translate("MainWindow", "osmolyte", None, QtGui.QApplication.UnicodeUTF8))
        self.macroMoleculeLabel.setText(QtGui.QApplication.translate("MainWindow", "macroMolecule", None, QtGui.QApplication.UnicodeUTF8))
        self.operatorLabel.setText(QtGui.QApplication.translate("MainWindow", "operator", None, QtGui.QApplication.UnicodeUTF8))
        self.setTypeLabel.setText(QtGui.QApplication.translate("MainWindow", "SetType", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.findSetButton.setText(QtGui.QApplication.translate("MainWindow", "Find Data Sets", None, QtGui.QApplication.UnicodeUTF8))
        self.plotButton.setText(QtGui.QApplication.translate("MainWindow", "Plot Selected", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Found Data Sets", None, QtGui.QApplication.UnicodeUTF8))
        self.clearPlotButton.setText(QtGui.QApplication.translate("MainWindow", "Clear Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.addToPlotButton.setText(QtGui.QApplication.translate("MainWindow", "Add To Selected", None, QtGui.QApplication.UnicodeUTF8))
        self.saveDataButton.setText(QtGui.QApplication.translate("MainWindow", "Save Data", None, QtGui.QApplication.UnicodeUTF8))

