# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Fri Jul  3 12:11:17 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1234, 752)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.centralWidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(70, 30, 1091, 591))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.browseDatabaseButton = QtGui.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browseDatabaseButton.sizePolicy().hasHeightForWidth())
        self.browseDatabaseButton.setSizePolicy(sizePolicy)
        self.browseDatabaseButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.browseDatabaseButton.setCheckable(False)
        self.browseDatabaseButton.setObjectName(_fromUtf8("browseDatabaseButton"))
        self.verticalLayout.addWidget(self.browseDatabaseButton)
        self.dataListWidget = QtGui.QListWidget(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dataListWidget.sizePolicy().hasHeightForWidth())
        self.dataListWidget.setSizePolicy(sizePolicy)
        self.dataListWidget.setObjectName(_fromUtf8("dataListWidget"))
        self.verticalLayout.addWidget(self.dataListWidget)
        self.plotSelected = QtGui.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotSelected.sizePolicy().hasHeightForWidth())
        self.plotSelected.setSizePolicy(sizePolicy)
        self.plotSelected.setObjectName(_fromUtf8("plotSelected"))
        self.verticalLayout.addWidget(self.plotSelected)
        self.addToListButton = QtGui.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addToListButton.sizePolicy().hasHeightForWidth())
        self.addToListButton.setSizePolicy(sizePolicy)
        self.addToListButton.setObjectName(_fromUtf8("addToListButton"))
        self.verticalLayout.addWidget(self.addToListButton)
        self.removeFromListButton = QtGui.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.removeFromListButton.sizePolicy().hasHeightForWidth())
        self.removeFromListButton.setSizePolicy(sizePolicy)
        self.removeFromListButton.setObjectName(_fromUtf8("removeFromListButton"))
        self.verticalLayout.addWidget(self.removeFromListButton)
        self.selectedDataListView = QtGui.QListView(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectedDataListView.sizePolicy().hasHeightForWidth())
        self.selectedDataListView.setSizePolicy(sizePolicy)
        self.selectedDataListView.setObjectName(_fromUtf8("selectedDataListView"))
        self.verticalLayout.addWidget(self.selectedDataListView)
        self.plotMultipleSelected = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.plotMultipleSelected.setObjectName(_fromUtf8("plotMultipleSelected"))
        self.verticalLayout.addWidget(self.plotMultipleSelected)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.tabWidget = QtGui.QTabWidget(self.horizontalLayoutWidget)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Triangular)
        self.tabWidget.setElideMode(QtCore.Qt.ElideRight)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.kSigma = QtGui.QWidget()
        self.kSigma.setObjectName(_fromUtf8("kSigma"))
        self.plotWidget = QtGui.QWidget(self.kSigma)
        self.plotWidget.setGeometry(QtCore.QRect(0, 0, 801, 561))
        self.plotWidget.setMaximumSize(QtCore.QSize(1600, 1600))
        self.plotWidget.setObjectName(_fromUtf8("plotWidget"))
        self.tabWidget.addTab(self.kSigma, _fromUtf8(""))
        self.t1 = QtGui.QWidget()
        self.t1.setObjectName(_fromUtf8("t1"))
        self.plotWidget1 = QtGui.QWidget(self.t1)
        self.plotWidget1.setGeometry(QtCore.QRect(0, 0, 801, 561))
        self.plotWidget1.setMaximumSize(QtCore.QSize(1600, 1600))
        self.plotWidget1.setObjectName(_fromUtf8("plotWidget1"))
        self.tabWidget.addTab(self.t1, _fromUtf8(""))
        self.cwEPR = QtGui.QWidget()
        self.cwEPR.setObjectName(_fromUtf8("cwEPR"))
        self.plotWidget2 = QtGui.QWidget(self.cwEPR)
        self.plotWidget2.setGeometry(QtCore.QRect(0, 0, 801, 561))
        self.plotWidget2.setMaximumSize(QtCore.QSize(1600, 1600))
        self.plotWidget2.setObjectName(_fromUtf8("plotWidget2"))
        self.tabWidget.addTab(self.cwEPR, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1234, 22))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuEdit = QtGui.QMenu(self.menuBar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(MainWindow)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.browseDatabaseButton.setText(_translate("MainWindow", "Browse Databse", None))
        self.plotSelected.setText(_translate("MainWindow", "Plot Selected Data Item", None))
        self.addToListButton.setText(_translate("MainWindow", "Add Data", None))
        self.removeFromListButton.setText(_translate("MainWindow", "Remove Data", None))
        self.plotMultipleSelected.setText(_translate("MainWindow", "Plot Selected Data Sets", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.kSigma), _translate("MainWindow", "kSigma", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.t1), _translate("MainWindow", "T1(power)", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.cwEPR), _translate("MainWindow", "cw-EPR", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit", None))

