# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Mon Jul 27 10:45:30 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1234, 697)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.SereisSelectionTabWidget = QtGui.QTabWidget(self.centralWidget)
        self.SereisSelectionTabWidget.setGeometry(QtCore.QRect(10, 10, 1211, 631))
        self.SereisSelectionTabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.SereisSelectionTabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.SereisSelectionTabWidget.setObjectName(_fromUtf8("SereisSelectionTabWidget"))
        self.selectDataSeries = QtGui.QWidget()
        self.selectDataSeries.setObjectName(_fromUtf8("selectDataSeries"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.selectDataSeries)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 1161, 591))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.browseDatabaseButton = QtGui.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browseDatabaseButton.sizePolicy().hasHeightForWidth())
        self.browseDatabaseButton.setSizePolicy(sizePolicy)
        self.browseDatabaseButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.browseDatabaseButton.setCheckable(False)
        self.browseDatabaseButton.setObjectName(_fromUtf8("browseDatabaseButton"))
        self.verticalLayout.addWidget(self.browseDatabaseButton)
        self.dataListWidget = QtGui.QListWidget(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dataListWidget.sizePolicy().hasHeightForWidth())
        self.dataListWidget.setSizePolicy(sizePolicy)
        self.dataListWidget.setObjectName(_fromUtf8("dataListWidget"))
        self.verticalLayout.addWidget(self.dataListWidget)
        self.plotSelected = QtGui.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotSelected.sizePolicy().hasHeightForWidth())
        self.plotSelected.setSizePolicy(sizePolicy)
        self.plotSelected.setObjectName(_fromUtf8("plotSelected"))
        self.verticalLayout.addWidget(self.plotSelected)
        self.selectedDataListView = QtGui.QListView(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectedDataListView.sizePolicy().hasHeightForWidth())
        self.selectedDataListView.setSizePolicy(sizePolicy)
        self.selectedDataListView.setObjectName(_fromUtf8("selectedDataListView"))
        self.verticalLayout.addWidget(self.selectedDataListView)
        self.plotMultipleSelected = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.plotMultipleSelected.setObjectName(_fromUtf8("plotMultipleSelected"))
        self.verticalLayout.addWidget(self.plotMultipleSelected)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.tabWidget = QtGui.QTabWidget(self.horizontalLayoutWidget)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Triangular)
        self.tabWidget.setElideMode(QtCore.Qt.ElideRight)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.kSigma = QtGui.QWidget()
        self.kSigma.setObjectName(_fromUtf8("kSigma"))
        self.plotWidget = QtGui.QWidget(self.kSigma)
        self.plotWidget.setGeometry(QtCore.QRect(0, 0, 801, 561))
        self.plotWidget.setMaximumSize(QtCore.QSize(1600, 1600))
        self.plotWidget.setObjectName(_fromUtf8("plotWidget"))
        self.tabWidget.addTab(self.kSigma, _fromUtf8(""))
        self.t1 = QtGui.QWidget()
        self.t1.setObjectName(_fromUtf8("t1"))
        self.plotWidget1 = QtGui.QWidget(self.t1)
        self.plotWidget1.setGeometry(QtCore.QRect(0, 0, 801, 561))
        self.plotWidget1.setMaximumSize(QtCore.QSize(1600, 1600))
        self.plotWidget1.setObjectName(_fromUtf8("plotWidget1"))
        self.tabWidget.addTab(self.t1, _fromUtf8(""))
        self.cwEPR = QtGui.QWidget()
        self.cwEPR.setObjectName(_fromUtf8("cwEPR"))
        self.plotWidget2 = QtGui.QWidget(self.cwEPR)
        self.plotWidget2.setGeometry(QtCore.QRect(0, 0, 801, 561))
        self.plotWidget2.setMaximumSize(QtCore.QSize(1600, 1600))
        self.plotWidget2.setObjectName(_fromUtf8("plotWidget2"))
        self.tabWidget.addTab(self.cwEPR, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.tabWidget)
        self.SereisSelectionTabWidget.addTab(self.selectDataSeries, _fromUtf8(""))
        self.veiwDataSeries = QtGui.QWidget()
        self.veiwDataSeries.setObjectName(_fromUtf8("veiwDataSeries"))
        self.verticalLayoutWidget = QtGui.QWidget(self.veiwDataSeries)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(70, 20, 268, 581))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label = QtGui.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setUnderline(True)
        font.setKerning(False)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_2.addWidget(self.label)
        self.kSigmaSeriesPlotRB = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.kSigmaSeriesPlotRB.setCheckable(True)
        self.kSigmaSeriesPlotRB.setObjectName(_fromUtf8("kSigmaSeriesPlotRB"))
        self.verticalLayout_2.addWidget(self.kSigmaSeriesPlotRB)
        self.kSigmaEPRDISeriesPlotRB = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.kSigmaEPRDISeriesPlotRB.setObjectName(_fromUtf8("kSigmaEPRDISeriesPlotRB"))
        self.verticalLayout_2.addWidget(self.kSigmaEPRDISeriesPlotRB)
        self.kSigmaT1SeriesPlotRB = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.kSigmaT1SeriesPlotRB.setObjectName(_fromUtf8("kSigmaT1SeriesPlotRB"))
        self.verticalLayout_2.addWidget(self.kSigmaT1SeriesPlotRB)
        self.kRhoSeriesPlotRB = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.kRhoSeriesPlotRB.setObjectName(_fromUtf8("kRhoSeriesPlotRB"))
        self.verticalLayout_2.addWidget(self.kRhoSeriesPlotRB)
        self.xiSeriesPlotRB = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.xiSeriesPlotRB.setObjectName(_fromUtf8("xiSeriesPlotRB"))
        self.verticalLayout_2.addWidget(self.xiSeriesPlotRB)
        self.tauSeriesPlotRB = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.tauSeriesPlotRB.setObjectName(_fromUtf8("tauSeriesPlotRB"))
        self.verticalLayout_2.addWidget(self.tauSeriesPlotRB)
        self.addT10DataButton = QtGui.QPushButton(self.verticalLayoutWidget)
        self.addT10DataButton.setCheckable(False)
        self.addT10DataButton.setObjectName(_fromUtf8("addT10DataButton"))
        self.verticalLayout_2.addWidget(self.addT10DataButton)
        self.label_4 = QtGui.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setUnderline(True)
        font.setKerning(False)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_2.addWidget(self.label_4)
        self.independentDimComboBox = QtGui.QComboBox(self.verticalLayoutWidget)
        self.independentDimComboBox.setEditable(True)
        self.independentDimComboBox.setObjectName(_fromUtf8("independentDimComboBox"))
        self.verticalLayout_2.addWidget(self.independentDimComboBox)
        self.label_3 = QtGui.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setUnderline(True)
        font.setKerning(False)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_2.addWidget(self.label_3)
        self.seriesDataListVeiw = QtGui.QListView(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.seriesDataListVeiw.sizePolicy().hasHeightForWidth())
        self.seriesDataListVeiw.setSizePolicy(sizePolicy)
        self.seriesDataListVeiw.setObjectName(_fromUtf8("seriesDataListVeiw"))
        self.verticalLayout_2.addWidget(self.seriesDataListVeiw)
        self.saveDataSeriesButton = QtGui.QPushButton(self.verticalLayoutWidget)
        self.saveDataSeriesButton.setObjectName(_fromUtf8("saveDataSeriesButton"))
        self.verticalLayout_2.addWidget(self.saveDataSeriesButton)
        self.label_6 = QtGui.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setUnderline(True)
        font.setKerning(False)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_2.addWidget(self.label_6)
        self.PlotErrorTextEdit = QtGui.QTextEdit(self.verticalLayoutWidget)
        self.PlotErrorTextEdit.setObjectName(_fromUtf8("PlotErrorTextEdit"))
        self.verticalLayout_2.addWidget(self.PlotErrorTextEdit)
        self.seriesPlotWidget = QtGui.QWidget(self.veiwDataSeries)
        self.seriesPlotWidget.setGeometry(QtCore.QRect(360, 20, 821, 581))
        self.seriesPlotWidget.setMaximumSize(QtCore.QSize(1600, 1600))
        self.seriesPlotWidget.setObjectName(_fromUtf8("seriesPlotWidget"))
        self.SereisSelectionTabWidget.addTab(self.veiwDataSeries, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1234, 22))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuEdit = QtGui.QMenu(self.menuBar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(MainWindow)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.menuFile.addAction(self.actionAbout)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(MainWindow)
        self.SereisSelectionTabWidget.setCurrentIndex(1)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.browseDatabaseButton.setText(_translate("MainWindow", "Browse Databse", None))
        self.plotSelected.setText(_translate("MainWindow", "Plot Selected Data Item", None))
        self.plotMultipleSelected.setText(_translate("MainWindow", "Plot Selected Data Sets", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.kSigma), _translate("MainWindow", "kSigma", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.t1), _translate("MainWindow", "T1(power)", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.cwEPR), _translate("MainWindow", "cw-EPR", None))
        self.SereisSelectionTabWidget.setTabText(self.SereisSelectionTabWidget.indexOf(self.selectDataSeries), _translate("MainWindow", "Select ODNP Data Series", None))
        self.label.setText(_translate("MainWindow", "Plot Type", None))
        self.kSigmaSeriesPlotRB.setText(_translate("MainWindow", "kSigma", None))
        self.kSigmaEPRDISeriesPlotRB.setText(_translate("MainWindow", "kSigma Normalized by EPR DI", None))
        self.kSigmaT1SeriesPlotRB.setText(_translate("MainWindow", "kSigma * T1(p=0)", None))
        self.kRhoSeriesPlotRB.setText(_translate("MainWindow", "kRho", None))
        self.xiSeriesPlotRB.setText(_translate("MainWindow", "Coupling Factor", None))
        self.tauSeriesPlotRB.setText(_translate("MainWindow", "Correlation Time (ps)", None))
        self.addT10DataButton.setText(_translate("MainWindow", "Add T10 Data to Set", None))
        self.label_4.setText(_translate("MainWindow", "Independent Dimension", None))
        self.label_3.setText(_translate("MainWindow", "Data Sets", None))
        self.saveDataSeriesButton.setText(_translate("MainWindow", "Save Data Series", None))
        self.label_6.setText(_translate("MainWindow", "Plotting Errors", None))
        self.SereisSelectionTabWidget.setTabText(self.SereisSelectionTabWidget.indexOf(self.veiwDataSeries), _translate("MainWindow", "Veiw ODNP Data Series", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))

